### ISSUE TITLE
Feature Request: It'd be nice to be able to insert series metadata since ePub v3 supports it.

### ISSUE THREAD

**Issue by AmandaCameron** [writingtoole/epub#3]
ePub v3 has support for adding series metadata. There's a couple of examples in [the group-position metadata attribute section](https://www.w3.org/publishing/epub3/epub-packages.html#sec-group-position) of the ePub spec. I'm not entirely clear on what the difference is between a `collection-type` of `series` and `set` though, but they are both rather similar, so maybe it could be an argument?

**Comment by writingtoole** [comment]
Huh, yeah, this'd be quite useful. I'll see about adding it in.

**Comment by writingtoole** [comment]
I think that commit should address this.
